version: '3'
services:
  oop_php:
    container_name: oop_php
    build:
      context: ./php/
    volumes:
      - ./nginx/www:/var/www

  oop_nginx:
    image: nginx:latest
    container_name: oop_nginx
    ports:
      - 81:80
    volumes:
      - ./nginx/www:/var/www
      - ./nginx/core:/etc/nginx/conf.d

  oop_mysql:
    image: mysql:8
    container_name: oop_mysql
    environment:
      MYSQL_DATABASE: oop
      MYSQL_ROOT_PASSWORD: root